CREATE TABLE "USER" (
	"UserId"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Nickname"	TEXT NOT NULL UNIQUE,
	"Age"	INTEGER,
	"Gender"	TEXT,
	"FirstName"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"DateRegister"	TEXT NOT NULL
);

CREATE TABLE "POSTS" (
	"PostId"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Title"	TEXT NOT NULL,
	"Category"	TEXT NOT NULL,
	"TextContent"	TEXT,
	"DateOfPublication"	DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"UserId"	INTEGER,
	FOREIGN KEY ("UserId") REFERENCES "USER"("UserId")
);

CREATE TABLE "COMMENTS" (
    "CommentsId" INTEGER PRIMARY KEY AUTOINCREMENT,
    "TextContent" TEXT NOT NULL,
    "CreateDate" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "UserId" INTEGER,
    "PostId" INTEGER,
    FOREIGN KEY ("PostId") REFERENCES "POSTS"("PostId"),
    FOREIGN KEY ("UserId") REFERENCES "USER"("UserId")
);

CREATE TABLE "PRIVATEMESSAGE" (
    "PrivateMessageId" INTEGER PRIMARY KEY AUTOINCREMENT,
    "TextContent" TEXT NOT NULL,
    "DateSent" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "SenderId" INTEGER,
    "RecipientId" INTEGER,
    FOREIGN KEY ("SenderId") REFERENCES "USER"("UserId"),
    FOREIGN KEY ("RecipientId") REFERENCES "USER"("UserId")
);